### Get the status
GET http://{{host}}:{{port}}/
Accept: application/json

### Get the containers list
GET http://{{host}}:{{port}}/containers
Accept: application/json

### Post a container request
POST http://{{host}}:{{port}}/containers/aabebd460822cd429cc37e03ce6151dca2f385cd6b9511eb0746e21e7f90fd3f
Content-Type: application/json

{
   "cpu_quota": 100000
}

###
