### Get the status
GET http://{{host}}:{{port}}/
Accept: application/json

### Get the containers list
GET http://{{host}}:{{port}}/containers
Accept: application/json

### Post a container request
POST http://{{host}}:{{port}}/containers/5bf316894b0aed043a16a159a3aba86c9fdf286a94cef87f6ad76a45812e4b68
Content-Type: application/json

{
   "cpu_quota": 100000
}

###
