### Get the status
GET http://{{host}}:{{port}}/
Accept: application/json

### Get the models
GET http://{{host}}:{{port}}/models
Accept: application/json

### Get a model
GET http://{{host}}:{{port}}/models/half_plus_two
Accept: application/json

### Get the models
PATCH http://{{host}}:{{port}}/models
Content-Type: application/json

{
  "model": "half_plus_two",
  "sla": 0.3
}

### Get the containers for a model
GET http://{{host}}:{{port}}/models/half_plus_two/containers
Accept: application/json

### Get the models by node
GET http://{{host}}:{{port}}/models/192.168.99.103
Accept: application/json

### Get the containers
GET http://{{host}}:{{port}}/containers
Accept: application/json

### Update the container
PATCH http://{{host}}:{{port}}/containers
Content-Type: application/json

{
  "container_id": "500bdb68dbf1",
  "cpu_quota": 300000
}


### Get the containers group by node
GET http://{{host}}:{{port}}/node/containers
Accept: application/json

### Get the containers by node
GET http://{{host}}:{{port}}/containers/192.168.99.103
Accept: application/json

### Post a model
POST http://{{host}}:{{port}}/models
Content-Type: application/json

{
  "model": "model_3",
  "version": 1
}
